dependencies = [
  "_ESAbstract.CreateHTML",
  "_ESAbstract.CreateMethodProperty",
]
spec = "https://www.ecma-international.org/ecma-262/6.0/#sec-string.prototype.sub"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/sub"

# Browsers which have always supported the feature are commented out.
[browsers]
# android = "*"
bb = "*"
# chrome = "*"
# edge = "*"
# edge_mob = "*"
firefox = "< 4"
# ios_chr = "*"
# ios_saf = "*"
ie = "*"
ie_mob = "*"
# opera = "*"
op_mini = "*"
# op_mob = "*"
# safari = "*"
firefox_mob = "< 4"
# samsung_mob = "*"

