dependencies = [
  "Reflect",
  "_ESAbstract.CreateMethodProperty",
  "_ESAbstract.Type",
  "_ESAbstract.ToPropertyKey",
  "_ESAbstract.Call"
]
spec = "https://tc39.github.io/ecma262/#sec-reflect.set"

[browsers]
android = "*"
bb = "*"
chrome = "*"
edge = "*"
edge_mob = "*"
firefox = "*"
firefox_mob = "*"
ie = "*"
ie_mob = "*"
ios_chr = "*"
ios_saf = "*"
op_mini = "*"
op_mob = "*"
opera = "*"
safari = "*"
samsung_mob = "*"

